on:
  release:
    types:
      - published


jobs:
  build:
    name: Build Homebrew Formula
    runs-on: ubuntu-latest

    steps:
      - name: Await PyPI Publication
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.ref }}
          check-name: Publish to PyPI
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v2

      - name: Build Formula
        run: pip install laureate && laureate

      - name: Upload Formula
        uses: actions/upload-artifact@v3
        with:
          name: schemarin.rb
          path: schemarin.rb

  publish:
    name: Publish Formula
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Formula
        uses: actions/download-artifact@v3
        with:
          name: schemarin.rb
          path: .

      - name: Push to Houkago Tea Tap
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source_file: schemarin.rb
          destination_repo: celsiusnarhwal/homebrew-htt
          destination_folder: Formula
          user_email: hello@celsiusnarhwal.dev
          user_name: celsiusnarhwal
          commit_message: Update formula for Schemarin https://github.com/celsiusnarhwal/schemarin