on:
  release:
    types:
      - published

  workflow_dispatch:


jobs:
  publish-package:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository

      - uses: actions/setup-python@v2
        name: Set Up Python

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -

      - name: Install Dependencies
        run: poetry install --without dev

      - name: Configure Credentials
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Build and Publish
        run: poetry publish --build

  build-formula:
    name: Build Homebrew Formula
    runs-on: ubuntu-latest
    needs: publish-package

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v2

      - name: Build Formula
        run: pip install laureate && laureate

      - name: Upload Formula
        uses: actions/upload-artifact@v3
        with:
          name: schemarin.rb
          path: schemarin.rb

  publish-formula:
    name: Publish Formula
    runs-on: ubuntu-latest
    needs: build-formula

    steps:
      - name: Download Formula
        uses: actions/download-artifact@v3
        with:
          name: schemarin.rb
          path: .

      - name: Push to Houkago Tea Tap
        run: |
          git config --global user.name "celsius narhwal" && git config --global user.email "
          gh repo clone celsiusnarhwal/homebrew-htt
          mv schemarin.rb homebrew-htt/Formula
          cd homebrew-htt
          git add Formula/schemarin.rb
          git commit -m "Update formula for Schemarin https://github.com/celsiusnarhwal/schemarin"
          git push
          
