on:
  release:
    types:
      - published

  workflow_dispatch:


jobs:
  publish-package:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
        with:
          submodules: recursive

      - uses: actions/setup-python@v2
        name: Set Up Python

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -

      - name: Install Dependencies
        run: poetry install --without dev

      - name: Configure Credentials
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Build and Publish
        run: poetry publish --build

  build-formula:
    name: Build Homebrew Formula
    runs-on: ubuntu-latest
    needs: publish-package

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v2

      - name: Build Formula
        run: |
          pip install laureate && laureate
          echo -e "# Homebrew formula for Schemarin. https://github.com/celsiusnarhwal/schemarin\n\n$(cat schemarin.rb)" > schemarin.rb

      - name: Upload Formula
        uses: actions/upload-artifact@v3
        with:
          name: schemarin.rb
          path: schemarin.rb

  build-bottles:
    name: Build Homebrew Bottles
    runs-on: macos-latest
    needs: build-formula

    steps:
      - name: Download Formula
        uses: actions/download-artifact@v3
        with:
          name: schemarin.rb
          path: .

      - name: Checkout Houkago Tea Tap
        uses: actions/checkout@v3
        with:
          repository: celsiusnarhwal/homebrew-htt
          path: houkago-tea-tap

      - name: Build Bottle
        run: |
          brew install --formula --build-bottle schemarin.rb
          ./houkago-tea-tap/bottle.sh schemarin
          cat /usr/local/Homebrew/Library/Taps/celsiusnarhwal/homebrew-htt/Formula/schemarin.rb > schemarin.rb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Formula
        uses: actions/upload-artifact@v3
        with:
          name: schemarin.rb
          path: schemarin.rb

      - name: Upload Bottles
        uses: actions/upload-artifact@v3
        with:
          name: schemarin.tar.gz
          path: schemarin.tar.gz
        

  publish-homebrew:
    name: Publish Homebrew Formula and Bottles
    runs-on: ubuntu-latest
    needs: build-bottles

    steps:
      - name: Download Formula
        uses: actions/download-artifact@v3
        with:
          name: schemarin.rb
          path: .

      - name: Download Bottles
        uses: actions/download-artifact@v3
        with:
          name: schemarin.tar.gz
          path: .

      - name: Set Git User Metadata
        run: |
          git config --global user.name "celsiusnarhwal"
          git config --global user.email "hello@celsiusnarhwal.dev"

      - name: Checkout Houkago Tea Tap
        uses: actions/checkout@v3
        with:
          repository: celsiusnarhwal/homebrew-htt
          path: houkago-tea-tap
          token: ${{ secrets.HTT_TOKEN }}

      - name: Publish Formula
        run: |
          mv schemarin.rb houkago-tea-tap/Formula/schemarin.rb
          cd houkago-tea-tap
          git add Formula/schemarin.rb
          git commit -m "Update formula for Schemarin https://github.com/celsiusnarhwal/schemarin"
          git push

      - name: Publish Bottle
        run: |
          mv schemarin.tar.gz houkago-tea-tap/Bottles/schemarin.tar.gz
          cd houkago-tea-tap/Bottles
          git lfs track schemarin.tar.gz
          git add schemarin.tar.gz .gitattributes
          git commit -m "Update bottle for Schemarin https://github.com/celsiusnarhwal/schemarin"
          git push